import type {
  BinauralConfig,
  FrequencyChoice,
  FrequencyLayer,
  IsochronicConfig,
  LanguageCode,
  RelaxMusicConfig,
  ResearchItem,
  SessionProtocol,
  SoundscapeConfig,
} from "./types";

export const FREQUENCY_CHOICES: FrequencyChoice[] = [
  {
    id: "solfeggio-174",
    group: "Solfeggio-style frequencies",
    label: "174 Hz - low grounding tone",
    frequency: 174,
    target: "carrier",
    evidence: "Historical spiritual teaching",
    note: "A modern Solfeggio-style value used as a symbolic relaxation tone.",
  },
  {
    id: "solfeggio-285",
    group: "Solfeggio-style frequencies",
    label: "285 Hz - restorative tradition tone",
    frequency: 285,
    target: "carrier",
    evidence: "Historical spiritual teaching",
    note: "A contemplative tradition preset, not a proven health effect.",
  },
  {
    id: "solfeggio-396",
    group: "Solfeggio-style frequencies",
    label: "396 Hz - release tradition tone",
    frequency: 396,
    target: "carrier",
    evidence: "Historical spiritual teaching",
    note: "Used in sound-practice communities with symbolic meaning.",
  },
  {
    id: "solfeggio-417",
    group: "Solfeggio-style frequencies",
    label: "417 Hz - change tradition tone",
    frequency: 417,
    target: "carrier",
    evidence: "Historical spiritual teaching",
    note: "A cultural preset for self-observation and meditation.",
  },
  {
    id: "solfeggio-528",
    group: "Solfeggio-style frequencies",
    label: "528 Hz - heart/repair tradition tone",
    frequency: 528,
    target: "carrier",
    evidence: "Historical spiritual teaching",
    note: "Commonly discussed online; treat claims cautiously.",
  },
  {
    id: "solfeggio-639",
    group: "Solfeggio-style frequencies",
    label: "639 Hz - connection tradition tone",
    frequency: 639,
    target: "carrier",
    evidence: "Historical spiritual teaching",
    note: "A symbolic sound-practice preset.",
  },
  {
    id: "solfeggio-741",
    group: "Solfeggio-style frequencies",
    label: "741 Hz - clarity tradition tone",
    frequency: 741,
    target: "carrier",
    evidence: "Historical spiritual teaching",
    note: "Use as an experiment variable and journal the result.",
  },
  {
    id: "solfeggio-852",
    group: "Solfeggio-style frequencies",
    label: "852 Hz - insight tradition tone",
    frequency: 852,
    target: "carrier",
    evidence: "Historical spiritual teaching",
    note: "A contemplative tradition value.",
  },
  {
    id: "solfeggio-963",
    group: "Solfeggio-style frequencies",
    label: "963 Hz - crown tradition tone",
    frequency: 963,
    target: "carrier",
    evidence: "Historical spiritual teaching",
    note: "A symbolic high-frequency preset, not a medical claim.",
  },
  {
    id: "earth-783",
    group: "Schumann and Earth resonance",
    label: "7.83 Hz - Schumann fundamental",
    frequency: 7.83,
    target: "beat",
    evidence: "Research-supported",
    note: "The approximate fundamental Schumann resonance; use as a beat or pulse variable.",
  },
  {
    id: "earth-14",
    group: "Schumann and Earth resonance",
    label: "14.3 Hz - Schumann harmonic",
    frequency: 14.3,
    target: "beat",
    evidence: "Research-supported",
    note: "Approximate Schumann harmonic, offered for careful experimentation.",
  },
  {
    id: "earth-203",
    group: "Schumann and Earth resonance",
    label: "20.8 Hz - Schumann harmonic",
    frequency: 20.8,
    target: "beat",
    evidence: "Research-supported",
    note: "Approximate Schumann harmonic, not a wellness guarantee.",
  },
  {
    id: "earth-1361",
    group: "Schumann and Earth resonance",
    label: "136.1 Hz - Earth-year inspired tone",
    frequency: 136.1,
    target: "carrier",
    evidence: "Historical spiritual teaching",
    note: "Used in contemplative tuning systems as an Earth-inspired carrier tone.",
  },
  {
    id: "beat-delta-05",
    group: "10 beat-building frequencies",
    label: "0.5 Hz - very slow delta beat",
    frequency: 0.5,
    target: "beat",
    evidence: "Hypothesis",
    note: "A very slow beat offset for personal relaxation experiments.",
  },
  {
    id: "beat-delta-2",
    group: "10 beat-building frequencies",
    label: "2 Hz - delta beat",
    frequency: 2,
    target: "beat",
    evidence: "Hypothesis",
    note: "A low beat offset; individual responses vary.",
  },
  {
    id: "beat-theta-4",
    group: "10 beat-building frequencies",
    label: "4 Hz - theta edge beat",
    frequency: 4,
    target: "beat",
    evidence: "Hypothesis",
    note: "A theta-range beat offset for meditation experiments.",
  },
  {
    id: "beat-theta-6",
    group: "10 beat-building frequencies",
    label: "6 Hz - theta beat",
    frequency: 6,
    target: "beat",
    evidence: "Hypothesis",
    note: "A common meditation beat offset.",
  },
  {
    id: "beat-alpha-8",
    group: "10 beat-building frequencies",
    label: "8 Hz - alpha/theta bridge beat",
    frequency: 8,
    target: "beat",
    evidence: "Hypothesis",
    note: "A beat offset near the alpha/theta boundary.",
  },
  {
    id: "beat-alpha-10",
    group: "10 beat-building frequencies",
    label: "10 Hz - alpha beat",
    frequency: 10,
    target: "beat",
    evidence: "Hypothesis",
    note: "A common relaxed-attention beat offset.",
  },
  {
    id: "beat-smr-12",
    group: "10 beat-building frequencies",
    label: "12 Hz - SMR-style beat",
    frequency: 12,
    target: "beat",
    evidence: "Hypothesis",
    note: "Inspired by sensorimotor rhythm discussions; not a clinical protocol.",
  },
  {
    id: "beat-beta-14",
    group: "10 beat-building frequencies",
    label: "14 Hz - low beta beat",
    frequency: 14,
    target: "beat",
    evidence: "Hypothesis",
    note: "A focus-style beat offset for self-observation.",
  },
  {
    id: "beat-beta-20",
    group: "10 beat-building frequencies",
    label: "20 Hz - beta beat",
    frequency: 20,
    target: "beat",
    evidence: "Hypothesis",
    note: "A higher beat offset; keep volume comfortable.",
  },
  {
    id: "beat-gamma-40",
    group: "10 beat-building frequencies",
    label: "40 Hz - gamma beat",
    frequency: 40,
    target: "beat",
    evidence: "Hypothesis",
    note: "A gamma-range beat offset used in some attention experiments.",
  },
  {
    id: "bentov-heart-aorta-67",
    group: "Bentov-inspired experiment frequencies",
    label: "6.7 Hz - Bentov heartbeat/aorta hypothesis",
    frequency: 6.7,
    target: "beat",
    evidence: "Hypothesis",
    note: "Inspired by Bentov-style body oscillator ideas; metaphorical, not established physiology.",
  },
  {
    id: "bentov-aortic-75",
    group: "Bentov-inspired experiment frequencies",
    label: "7.5 Hz - Bentov oscillator experiment",
    frequency: 7.5,
    target: "beat",
    evidence: "Hypothesis",
    note: "A Bentov-inspired experimental beat value for journaling.",
  },
  {
    id: "bentov-schumann-783",
    group: "Bentov-inspired experiment frequencies",
    label: "7.83 Hz - Bentov/Schumann bridge",
    frequency: 7.83,
    target: "beat",
    evidence: "Hypothesis",
    note: "Connects Bentov-style resonance language with Schumann-resonance discussion.",
  },
  {
    id: "bentov-alpha-8",
    group: "Bentov-inspired experiment frequencies",
    label: "8 Hz - Bentov alpha bridge",
    frequency: 8,
    target: "beat",
    evidence: "Hypothesis",
    note: "A low alpha experiment value.",
  },
  {
    id: "bentov-alpha-10",
    group: "Bentov-inspired experiment frequencies",
    label: "10 Hz - Bentov coherent attention",
    frequency: 10,
    target: "beat",
    evidence: "Hypothesis",
    note: "A relaxed attention beat value for personal experimentation.",
  },
  {
    id: "bentov-spinal-33",
    group: "Bentov-inspired experiment frequencies",
    label: "33 Hz - spinal cascade hypothesis",
    frequency: 33,
    target: "beat",
    evidence: "Hypothesis",
    note: "A speculative Bentov-inspired experiment value, not a biological claim.",
  },
  {
    id: "bentov-432",
    group: "Bentov-inspired experiment frequencies",
    label: "432 Hz - harmonic carrier experiment",
    frequency: 432,
    target: "carrier",
    evidence: "Historical spiritual teaching",
    note: "A common contemplative tuning value used as a carrier tone.",
  },
  {
    id: "bentov-528",
    group: "Bentov-inspired experiment frequencies",
    label: "528 Hz - harmonic carrier experiment",
    frequency: 528,
    target: "carrier",
    evidence: "Historical spiritual teaching",
    note: "A common sound-practice value used here as an experiment carrier.",
  },
];

interface LanguagePack {
  appName: string;
  tagline: string;
  dashboard: string;
  frequencyLab: string;
  sessionBuilder: string;
  visualization: string;
  journal: string;
  analytics: string;
  assistant: string;
  research: string;
  start: string;
  stop: string;
  save: string;
  export: string;
  demoMode: string;
  safety: string;
  noMedicalClaims: string;
  pureTones: string;
  binaural: string;
  isochronic: string;
  moodBefore: string;
  moodAfter: string;
  notes: string;
  ask: string;
}

export const LANGUAGE_PACKS: Record<LanguageCode, LanguagePack> = {
  en: {
    appName: "Resonance Lab",
    tagline: "A personal frequency, meditation, and self-observation laboratory.",
    dashboard: "Dashboard",
    frequencyLab: "Frequency Lab",
    sessionBuilder: "Session Builder",
    visualization: "Visualization",
    journal: "Research Journal",
    analytics: "Analytics",
    assistant: "AI Research Assistant",
    research: "Research Database",
    start: "Start audio",
    stop: "Stop",
    save: "Save",
    export: "Export",
    demoMode: "Demo-safe browser mode",
    safety: "Safety protocol active",
    noMedicalClaims:
      "For education, meditation, relaxation, creativity, and self-observation only. Not medical advice, diagnosis, treatment, or a substitute for professional care.",
    pureTones: "Pure tones",
    binaural: "Binaural beats",
    isochronic: "Isochronic pulses",
    moodBefore: "Mood before",
    moodAfter: "Mood after",
    notes: "Notes",
    ask: "Ask",
  },
  th: {
    appName: "Resonance Lab",
    tagline: "ห้องทดลองส่วนตัวสำหรับเสียง สมาธิ และการสังเกตตนเอง",
    dashboard: "แดชบอร์ด",
    frequencyLab: "ห้องทดลองความถี่",
    sessionBuilder: "สร้างเซสชัน",
    visualization: "ภาพเคลื่อนไหว",
    journal: "บันทึกการทดลอง",
    analytics: "วิเคราะห์",
    assistant: "ผู้ช่วยวิจัย AI",
    research: "ฐานข้อมูลงานวิจัย",
    start: "เริ่มเสียง",
    stop: "หยุด",
    save: "บันทึก",
    export: "ส่งออก",
    demoMode: "โหมดสาธิตบนเบราว์เซอร์",
    safety: "เปิดระบบความปลอดภัย",
    noMedicalClaims:
      "ใช้เพื่อการศึกษา สมาธิ การผ่อนคลาย ความคิดสร้างสรรค์ และการสังเกตตนเองเท่านั้น ไม่ใช่คำแนะนำทางการแพทย์ การวินิจฉัย หรือการรักษา",
    pureTones: "เสียงบริสุทธิ์",
    binaural: "ไบนอรัลบีต",
    isochronic: "ไอโซโครนิกพัลส์",
    moodBefore: "อารมณ์ก่อน",
    moodAfter: "อารมณ์หลัง",
    notes: "บันทึก",
    ask: "ถาม",
  },
  zh: {
    appName: "Resonance Lab",
    tagline: "个人频率、冥想与自我观察实验室。",
    dashboard: "仪表盘",
    frequencyLab: "频率实验室",
    sessionBuilder: "课程构建器",
    visualization: "可视化",
    journal: "研究日志",
    analytics: "分析",
    assistant: "AI 研究助手",
    research: "研究数据库",
    start: "开始音频",
    stop: "停止",
    save: "保存",
    export: "导出",
    demoMode: "浏览器安全演示模式",
    safety: "安全协议已启用",
    noMedicalClaims:
      "仅用于教育、冥想、放松、创造力和自我观察。不是医疗建议、诊断、治疗或专业护理的替代品。",
    pureTones: "纯音",
    binaural: "双耳节拍",
    isochronic: "等时脉冲",
    moodBefore: "之前心情",
    moodAfter: "之后心情",
    notes: "记录",
    ask: "提问",
  },
  ja: {
    appName: "Resonance Lab",
    tagline: "周波数、瞑想、自己観察のための個人ラボ。",
    dashboard: "ダッシュボード",
    frequencyLab: "周波数ラボ",
    sessionBuilder: "セッション作成",
    visualization: "ビジュアル",
    journal: "研究ジャーナル",
    analytics: "分析",
    assistant: "AI 研究アシスタント",
    research: "研究データベース",
    start: "音を開始",
    stop: "停止",
    save: "保存",
    export: "書き出し",
    demoMode: "ブラウザ内デモモード",
    safety: "安全プロトコル有効",
    noMedicalClaims:
      "教育、瞑想、リラクゼーション、創造性、自己観察のみを目的とします。医療助言、診断、治療、専門的ケアの代替ではありません。",
    pureTones: "純音",
    binaural: "バイノーラルビート",
    isochronic: "アイソクロニックパルス",
    moodBefore: "開始前の気分",
    moodAfter: "終了後の気分",
    notes: "メモ",
    ask: "質問",
  },
  ko: {
    appName: "Resonance Lab",
    tagline: "주파수, 명상, 자기 관찰을 위한 개인 실험실.",
    dashboard: "대시보드",
    frequencyLab: "주파수 랩",
    sessionBuilder: "세션 빌더",
    visualization: "시각화",
    journal: "연구 저널",
    analytics: "분석",
    assistant: "AI 연구 도우미",
    research: "연구 데이터베이스",
    start: "오디오 시작",
    stop: "정지",
    save: "저장",
    export: "내보내기",
    demoMode: "브라우저 데모 모드",
    safety: "안전 프로토콜 활성화",
    noMedicalClaims:
      "교육, 명상, 이완, 창의성, 자기 관찰 목적입니다. 의학적 조언, 진단, 치료 또는 전문 진료의 대체물이 아닙니다.",
    pureTones: "순음",
    binaural: "바이노럴 비트",
    isochronic: "아이소크로닉 펄스",
    moodBefore: "전 기분",
    moodAfter: "후 기분",
    notes: "노트",
    ask: "질문",
  },
  es: {
    appName: "Resonance Lab",
    tagline: "Un laboratorio personal de frecuencia, meditacion y autoobservacion.",
    dashboard: "Panel",
    frequencyLab: "Laboratorio",
    sessionBuilder: "Sesiones",
    visualization: "Visualizacion",
    journal: "Diario",
    analytics: "Analitica",
    assistant: "Asistente AI",
    research: "Investigacion",
    start: "Iniciar audio",
    stop: "Detener",
    save: "Guardar",
    export: "Exportar",
    demoMode: "Modo demo en navegador",
    safety: "Protocolo de seguridad activo",
    noMedicalClaims:
      "Solo para educacion, meditacion, relajacion, creatividad y autoobservacion. No es consejo medico, diagnostico, tratamiento ni sustituto de atencion profesional.",
    pureTones: "Tonos puros",
    binaural: "Binaural",
    isochronic: "Isochronico",
    moodBefore: "Animo antes",
    moodAfter: "Animo despues",
    notes: "Notas",
    ask: "Preguntar",
  },
  de: {
    appName: "Resonance Lab",
    tagline: "Ein persoenliches Labor fuer Frequenz, Meditation und Selbstbeobachtung.",
    dashboard: "Dashboard",
    frequencyLab: "Frequenzlabor",
    sessionBuilder: "Sitzungen",
    visualization: "Visualisierung",
    journal: "Journal",
    analytics: "Analytik",
    assistant: "AI Assistent",
    research: "Forschung",
    start: "Audio starten",
    stop: "Stoppen",
    save: "Speichern",
    export: "Exportieren",
    demoMode: "Browser-Demomodus",
    safety: "Sicherheitsprotokoll aktiv",
    noMedicalClaims:
      "Nur fuer Bildung, Meditation, Entspannung, Kreativitaet und Selbstbeobachtung. Keine medizinische Beratung, Diagnose, Behandlung oder Ersatz fuer professionelle Betreuung.",
    pureTones: "Reintoene",
    binaural: "Binaurale Beats",
    isochronic: "Isochrone Pulse",
    moodBefore: "Stimmung vorher",
    moodAfter: "Stimmung nachher",
    notes: "Notizen",
    ask: "Fragen",
  },
  fr: {
    appName: "Resonance Lab",
    tagline: "Un laboratoire personnel de frequence, meditation et observation de soi.",
    dashboard: "Tableau",
    frequencyLab: "Laboratoire",
    sessionBuilder: "Sessions",
    visualization: "Visualisation",
    journal: "Journal",
    analytics: "Analyse",
    assistant: "Assistant IA",
    research: "Recherche",
    start: "Demarrer l'audio",
    stop: "Arreter",
    save: "Enregistrer",
    export: "Exporter",
    demoMode: "Mode demo navigateur",
    safety: "Protocole de securite actif",
    noMedicalClaims:
      "Uniquement pour education, meditation, relaxation, creativite et auto-observation. Ce n'est pas un conseil medical, diagnostic, traitement ni substitut a des soins professionnels.",
    pureTones: "Tons purs",
    binaural: "Binaural",
    isochronic: "Impulsions isochrones",
    moodBefore: "Humeur avant",
    moodAfter: "Humeur apres",
    notes: "Notes",
    ask: "Demander",
  },
};

export const DEFAULT_LAYERS: FrequencyLayer[] = [
  {
    id: "earth-alpha",
    label: "Schumann-inspired low carrier",
    frequency: 136.1,
    volume: 0.24,
    pan: -0.18,
    waveform: "sine",
    enabled: true,
    note: "Used here as an artistic carrier, not a proven therapeutic signal.",
  },
  {
    id: "focus-harmonic",
    label: "Soft focus harmonic",
    frequency: 432,
    volume: 0.18,
    pan: 0.12,
    waveform: "triangle",
    enabled: true,
    note: "Common in sound-practice communities; effects should be self-observed.",
  },
  {
    id: "clarity-air",
    label: "High clarity overtone",
    frequency: 963,
    volume: 0.08,
    pan: 0.32,
    waveform: "sine",
    enabled: false,
    note: "A Solfeggio-associated value treated as cultural context, not fact.",
  },
];

export const DEFAULT_BINAURAL: BinauralConfig = {
  carrier: 220,
  beat: 8,
  volume: 0.22,
};

export const DEFAULT_ISOCHRONIC: IsochronicConfig = {
  carrier: 174,
  pulse: 6,
  volume: 0.2,
};

export const DEFAULT_SOUNDSCAPE: SoundscapeConfig = {
  enabled: true,
  type: "pink",
  volume: 0.08,
};

export const DEFAULT_RELAX_MUSIC: RelaxMusicConfig = {
  enabled: true,
  rootFrequency: 216,
  volume: 0.12,
  warmth: 0.64,
};

export const DEFAULT_PROTOCOLS: SessionProtocol[] = [
  {
    id: "relaxation-entry",
    title: "Relaxation Entry",
    module: "Relaxation",
    durationMinutes: 12,
    breathRate: 6,
    intention: "Observe the body without trying to fix it.",
    affirmation: "I can notice, soften, and return to the present moment.",
    visualization:
      "Imagine a quiet silver line moving with each breath, expanding on inhale and settling on exhale.",
    mode: "binaural",
  },
  {
    id: "focused-builder",
    title: "Focused Builder",
    module: "Focus",
    durationMinutes: 18,
    breathRate: 7,
    intention: "Prepare one clear work block.",
    affirmation: "Attention can become simple when the next action is visible.",
    visualization:
      "Picture a mission-control console with one illuminated task tile and every other signal dimmed.",
    mode: "pure",
  },
  {
    id: "creative-rehearsal",
    title: "Creative Rehearsal",
    module: "Visualization",
    durationMinutes: 15,
    breathRate: 5,
    intention: "Explore a desired outcome as a rehearsal, not a guarantee.",
    affirmation: "I can practice the feeling of showing up with clarity.",
    visualization:
      "Walk through tomorrow's best version of one moment, noticing sensory detail and choice points.",
    mode: "isochronic",
  },
];

export const EXPLORATION_MODULES = [
  "Relaxation",
  "Focus",
  "Creativity",
  "Visualization",
  "Deep meditation",
  "Self-reflection",
  "Goal rehearsal",
  "Gratitude practice",
];

export const RESEARCH_LIBRARY: ResearchItem[] = [
  {
    title: "Auditory beat stimulation and subjective state",
    level: "Research-supported",
    summary:
      "Some studies examine whether rhythmic auditory stimulation correlates with attention, relaxation, or mood measures. Results vary by protocol, population, and outcome.",
    usage:
      "Use as a cautious starting point for self-observation. Do not generalize a personal result to a medical claim.",
  },
  {
    title: "Bentov-inspired oscillator model",
    level: "Hypothesis",
    summary:
      "Bentov's exploratory writing frames the body as an oscillating system. Resonance Lab treats this as a metaphor and design lens, not established neuroscience.",
    usage:
      "Useful for visualization prompts and experiment design language when clearly labeled as hypothesis.",
  },
  {
    title: "Solfeggio frequency traditions",
    level: "Historical spiritual teaching",
    summary:
      "Modern sound-work communities associate specific values such as 174, 396, 528, and 963 Hz with contemplative meaning. These associations are cultural and experiential.",
    usage:
      "Offer as optional symbolic presets while avoiding claims that a number causes a specific health outcome.",
  },
  {
    title: "Personal session reports",
    level: "User experience",
    summary:
      "Mood, focus, energy, sleep quality, and stress perception entries are subjective and context-sensitive.",
    usage:
      "Graph as personal trend data and invite reflection rather than proof.",
  },
];

export const ASSISTANT_STARTER = {
  prompt:
    "Build a 15-minute calm-focus session. Explain what you are checking, what signals I should watch, and how to journal the result without making medical claims.",
  response:
    "I will design a bounded sound-and-breath experiment, show the evidence labels, name the safety checks, and give you a short journal loop. Use it for relaxation and self-observation only, not diagnosis or treatment.",
};
